# Generated by Django 3.2.7 on 2023-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfo',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailinfo',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
